### ISSUE TITLE
allow opcode notation

### ISSUE THREAD

**Issue by x87** [sannybuilder/library#35]
toggle between default display (ClassName.ClassMember) and low-level opcode notation:

When class notation is on:
```
[var handle: Player] = Player.Create(model: int, x: float, y: float, z: float)
[var handle: CarGenerator] = CarGenerator.Create(x: float, y: float, z: float, heading: float, modelId: int, primaryColor: int, secondaryColor: int, forceSpawn: bool, alarmChance: int, doorLockChance: int, minDelay: int, maxDelay: int)
```

When opcode notation is on

```
0053: create_player model [int] x [float] y [float] z [float] store_to [var handle: Player]
014B: create_car_generator x [float] y [float] z [float] heading [float] modelId [int] primaryColor [int] secondaryColor [int] forceSpawn [bool] alarmChance [int] doorLockChance [int] minDelay [int] maxDelay [int] store_to [var handle: CarGenerator]
```

**Comment by wmysterio** [comment]
I think there is a lot of duplicate information in the opcode. Perhaps they just need to be highlighted in color:

![](https://i.ibb.co/DwBKrMh/image.png)

P. S. I liked the description `[int] x`.

**Comment by x87** [comment]
highlighting params is an interesting idea. 

but if you copy the opcode line to sanny there will be no extra information on what `self x y z` are, so you will have to constantly look back into the library. this is why I think having both name and type is essential. It is like today we have a word and a value in opcodes.txt for parameters

`01B4: set_player $PLAYER_CHAR can_move 0`

>I liked the description [int] x.

you mean when the type is written in front of a parameter?

**Comment by x87** [comment]
@wmysterio added highlighting, what do you think?

**Comment by XMDS** [comment]
@x87  Whether to consider changing to a different color.  I don't think there is anything wrong with yellow, but the original display color of the class is green. If the parameter declaration is yellow, it is not very obvious?  In addition, do you consider the same highlighting of commands that use keywords?  Another problem is that it is recommended to have a dividing line or a blank line between the class form and the OP form, because they have the same color and are not so comfortable when arranged together.

**Comment by x87** [comment]
@XMDS 
>consider changing to a different color.

what about cyan color?
![image](https://user-images.githubusercontent.com/5698288/121793340-26397a00-cbcc-11eb-8470-c8fd8e93f9b9.png)

>consider the same highlighting of commands that use keywords

highlighting is implemented in all kinds of presentation. If I missed something, let me know.

**Comment by wmysterio** [comment]
> but if you copy the opcode line to sanny there will be no extra information on what self x y z are, so you will have to constantly look back into the library

Good point. Is it possible to intercept the procedure for copying, dragging and dropping text? You can try to replace the copied text with the one that has descriptions of types and names.

> added highlighting, what do you think?

Looks nice. I don't know about colors, I chose yellow just for example. If anyone has a better option, let him suggest.

> you mean when the type is written in front of a parameter?

Yes. I'm just used to reading the description of the parameter before the parameter itself, that is, everything was read from left to right (SB, C++, C#, Java, PHP). Otherwise, you have to get used to it) But this is not critical.
