### ISSUE TITLE
add platform tags

### ISSUE THREAD

**Issue by x87** [sannybuilder/library#38]
- platform_any
- platform_pc
- platform_mobile
- platform_console

could be multi-choice

**Comment by x87** [comment]
also need a filter by platforms.

initially tag all commands with `platform_any`

**Comment by x87** [comment]
@XMDS what are your thoughts on the list of platforms for each game? Do you think that the generic names I added above ☝️ would cover all use cases or we might need more specific ones, like: `platform_xbox360`, etc? please share

**Comment by XMDS** [comment]
Yes it is.  I think that's it.  We do not need to classify the host platform specifically.  Because most of their commands are universal, only a few commands are independent of a certain platform.  Moreover, the mainstream of the GTA 3D series of games is still on PC and Mobile, and the console version of the game lacks modified MOD plug-ins. We do not need to be specific to a certain platform. It is like the mobile platform is divided into Android and ios, but there is no difference in essence.

**Comment by x87** [comment]
>the mobile platform is divided into Android and ios, but there is no difference in essence.

but speaking of CLEO opcodes, for example, there is a difference, since some commands only exist for Android version of the game.

Also some commands only exist in a particular game version/release. For example, 
0482 SET_THREAT_REACTION_RANGE_MULTIPLIER // only work with GTA 3 v1.0, does not work with GTA3 1.1
[059C](https://gtamods.com/wiki/059C) in Vice City have different parameters for US and JP versions.
[059A](https://library.sannybuilder.com/#/sa/default/059A) is not a `return_false` command, but presumably it returns true on the Australian release of the game.

In this sense, for accurate descriptions and covering all possible game releases we have to think about extra dimension for commands grouping in addition to extension and id. Game version?

**Comment by x87** [comment]
```
Game
 |-- Platform (platform_any, platform_pc, platform_console, platform_mobile, platform_android, platform_ios)
   |-- Version (version_any, version_10, version_11, version_20, version_30)
     |-- Extension (default, cleo, ...)
       |-- Command Id (0000, 0001, 0002...)
```
In the absolute majority of cases we are interested in `platform_pc` and `version_10` of each game. However for the sake of documentation other combinations should be considered too, since they do have differences.

**Comment by XMDS** [comment]
> but speaking of CLEO opcodes, for example, there is a difference, since some commands only exist for Android version of the game.
> 
In the original command, Android and IOS are the same.  Regarding the new commands of Android CLEO, as mentioned before, we will expand on CLEO.  Also, I guess @squ1dd13 will eventually add some new Android commands to ios CLEO.

> Also some commands only exist in a particular game version/release. For example, 
> 0482 SET_THREAT_REACTION_RANGE_MULTIPLIER // only work with GTA 3 v1.0, does not work with GTA3 1.1
> [059C](https://gtamods.com/wiki/059C) in Vice City have different parameters for US and JP versions.
> [059A](https://library.sannybuilder.com/#/sa/default/059A) is not a `return_false` command, but presumably it returns true on the Australian release of the game.
> 
> In this sense, for accurate descriptions and covering all possible game releases we have to think about extra dimension for commands grouping in addition to extension and id. Game version?
> 
> 

It is really necessary to distinguish between game versions.  However, the 059A in the example determines whether it is an Australian version of the game, even if it is running on the US version, it is normal to return false.  This command only returns true in the Australian version. There is not much need for this command to be marked as a regionally released version.  Because it can also be used in other versions.

**Comment by x87** [comment]
GTA III

Platform: PC/PS2 (US/EUR v1.0) - supports 0000 through 0482
Platform: PC v1.1/Steam - does not support 0482=1,set_threat_reaction_range_multiplier 
//android/ios - used 03A8, 03A9

Vice City 
Platform: PC/PS2 (US,EU,AUS region, both 1.0/1.1) - supports 0000 through 05A8
Platform: PC/PS2 (JP region) - changed 059C and removed 059D through 05A8
Platform: Mobile (android/ios) - added 05a9, 05aa, 05ab, 05ac


San Andreas
v1.0-2.0 (PC/all regions) - supports 0000 through 0A4E
mobile (ios/android) - changed 0242, added 0A4F through 0A8D
remastered (next-gen consoles) - added 0A8E, 0A8F, 0A90

**Comment by x87** [comment]
Added Platform tags

![image](https://user-images.githubusercontent.com/5698288/141044249-4e64f799-d382-4f68-b757-a1fc676e62e4.png)

Can be either `Any` or a combination of `PC`/`Mobile`/`Console` (but not all three)

Default value for platforms is `Any`

**Comment by x87** [comment]
Added version tags (unique for each game), example for San Andreas
![Screen Shot 2021-11-24 at 00 51 36](https://user-images.githubusercontent.com/5698288/143182508-0005f464-94f7-4535-833e-b67efac43d37.png)

extra versions could be added if there is a need.

game+platform+version should provide a way to describe any possible variation of a command.
